# Generated by Django 5.1.4 on 2026-05-17 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Ubicación')),
                ('equipment_id', models.CharField(max_length=60, verbose_name='Identificador del equipo')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto')], default='abierto', max_length=20, verbose_name='Estado')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Nota de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
